<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Api\CabangController;
use App\Http\Controllers\authentications\Login;
use App\Http\Controllers\authentications\Logout;
use App\Http\Controllers\authentications\ForgotPassword;
use App\Http\Controllers\dashboard\DashboardController;
use App\Http\Controllers\akun\ProfilController;
use App\Http\Controllers\akun\UbahSandiController;
use App\Http\Controllers\setting\RegistrasiUser;
use App\Http\Controllers\setting\PengumumanController;
use App\Http\Controllers\setting\ProfilePerusahaanController;
use App\Http\Controllers\setting\CoaController;
use App\Http\Controllers\setting\KaryawanController;
use App\Http\Controllers\setting\ChangeCabangController;
use App\Http\Controllers\setting\JenisPekerjaanController;
use App\Http\Controllers\setting\PanelPekerjaanController;
use App\Http\Controllers\setting\PosisiPekerjaanController;
use App\Http\Controllers\setting\TarifPpnController;
use App\Http\Controllers\setting\MenuController;
use App\Http\Controllers\setting\GroupController;
use App\Http\Controllers\setting\UserPrivilegeController;
use App\Http\Controllers\setting\GroupPrivilegeController;
use App\Http\Controllers\setting\CabangPrivilegeController;
use App\Http\Controllers\setting\PeriodePembukuanController;
use App\Http\Controllers\setting\PenomoranTransaksiController;
use App\Http\Controllers\setting\PrinterController;
use App\Http\Controllers\setting\BackupDBController;
use App\Http\Controllers\setting\JenisKendaraanController;
use App\Http\Controllers\setting\MerekKendaraanController;
use App\Http\Controllers\setting\TipeKendaraanController;
use App\Http\Controllers\setting\LogActivityController;
use App\Http\Controllers\setting\LoginActivityController;
use App\Http\Controllers\setting\ParameterController;
use App\Http\Controllers\customer_service\PemilikController;
use App\Http\Controllers\customer_service\KendaraanController;
use App\Http\Controllers\customer_service\AsuransiController;
use App\Http\Controllers\customer_service\PelangganController;
use App\Http\Controllers\customer_service\MarketingController;
use App\Http\Controllers\customer_service\PerantaraController;
use App\Http\Controllers\customer_service\SpkController;
use App\Http\Controllers\customer_service\SpkBatalController;
use App\Http\Controllers\customer_service\SpkTutupController;
use App\Http\Controllers\customer_service\SpkKeluarController;
use App\Http\Controllers\customer_service\InvoiceOrController;
use App\Http\Controllers\customer_service\TandaTerimaInvoiceOrController;
use App\Http\Controllers\customer_service\LaporanSpkController;
use App\Http\Controllers\customer_service\LaporanKendaraanController;
use App\Http\Controllers\customer_service\LaporanPosisiPerbaikanController;
use App\Http\Controllers\customer_service\LaporanInvoiceController;
use App\Http\Controllers\customer_service\LaporanOutstandingController;
use App\Http\Controllers\customer_service\LaporanKwitansiController;
use App\Http\Controllers\administrasi\FotoPekerjaanController;
use App\Http\Controllers\administrasi\KonsepEstimasiController;
use App\Http\Controllers\administrasi\EstimasiController;
use App\Http\Controllers\administrasi\KirimEstimasiController;
use App\Http\Controllers\administrasi\KewajibanController;
use App\Http\Controllers\administrasi\JadwalTurunLapController;
use App\Http\Controllers\administrasi\ProgressKerjaController;
use App\Http\Controllers\administrasi\PosisiPerbaikanController;
use App\Http\Controllers\administrasi\EstimasiDisetujuiController;
use App\Http\Controllers\administrasi\SalvageController;
use App\Http\Controllers\administrasi\KirimSalvageController;
use App\Http\Controllers\administrasi\InvoiceController;
use App\Http\Controllers\administrasi\TandaTerimaInvoiceController;
use App\Http\Controllers\administrasi\TerimaDokumenKlaimController;
use App\Http\Controllers\administrasi\LaporanEstimasiBelumDibuatController;
use App\Http\Controllers\administrasi\LaporanEstimasiBelumDikirimController;
use App\Http\Controllers\administrasi\LaporanRekapEstimasiController;
use App\Http\Controllers\administrasi\LaporanRincianEstimasiController;
use App\Http\Controllers\administrasi\LaporanEstimasiPerTahunController;
use App\Http\Controllers\administrasi\LaporanEstimasiDisetujuiController;
use App\Http\Controllers\administrasi\LaporanInsentifKwitansiController;
use App\Http\Controllers\administrasi\LaporanInsentifPembayaranController;
use App\Http\Controllers\administrasi\LaporanInsentifMarketingController;
use App\Http\Controllers\administrasi\LaporanInsentifSTController;
use App\Http\Controllers\administrasi\LaporanAgingPenawaranController;
use App\Http\Controllers\administrasi\LaporanAgingPenagihanController;
use App\Http\Controllers\administrasi\LaporanKomisiSurveyorController;
use App\Http\Controllers\administrasi\LaporanRekapPointPanelController;
use App\Http\Controllers\gudang\BahanController;
use App\Http\Controllers\gudang\SparepartController;
use App\Http\Controllers\gudang\CatController;
use App\Http\Controllers\gudang\PemasokController;
use App\Http\Controllers\gudang\UmumController;
use App\Http\Controllers\gudang\PemakaianBahanController;
use App\Http\Controllers\gudang\PermintaanBarangController;
use App\Http\Controllers\gudang\OrderPembelianController;
use App\Http\Controllers\gudang\InputPembelianController;
use App\Http\Controllers\gudang\ReturPembelianController;
use App\Http\Controllers\gudang\PengeluaranBarangController;
use App\Http\Controllers\gudang\StockOpnameController;
use App\Http\Controllers\gudang\TutupBukuController;
use App\Http\Controllers\gudang\LaporanPembelianBahanController;
use App\Http\Controllers\gudang\LaporanPembelianCatController;
use App\Http\Controllers\gudang\LaporanPembelianSparepartController;
use App\Http\Controllers\gudang\LaporanGudangBahanController;
use App\Http\Controllers\gudang\LaporanGudangCatController;
use App\Http\Controllers\gudang\LaporanGudangSparepartController;
use App\Http\Controllers\gudang\LaporanPengeluaranBahanController;
use App\Http\Controllers\gudang\LaporanPengeluaranCatController;
use App\Http\Controllers\gudang\LaporanPengeluaranSparepartController;
use App\Http\Controllers\gudang\LaporanReturSparepartController;
use App\Http\Controllers\gudang\LaporanAnalisaPemakaianBahanController;
use App\Http\Controllers\gudang\LaporanAnalisaPemakaianCatController;
use App\Http\Controllers\gudang\LaporanKontrolPemakaianBahanController;
use App\Http\Controllers\keuangan\BankController;
use App\Http\Controllers\keuangan\RekeningController;
use App\Http\Controllers\keuangan\BuktiPenerimaanController;
use App\Http\Controllers\keuangan\InputKasController;
use App\Http\Controllers\keuangan\InputBankController;
use App\Http\Controllers\keuangan\HistorySpkController;
use App\Http\Controllers\keuangan\UangMukaPenjualanController;
use App\Http\Controllers\keuangan\UangMukaPembelianController;
use App\Http\Controllers\keuangan\PenerimaanGabunganController;
use App\Http\Controllers\keuangan\PembayaranGabunganController;
use App\Http\Controllers\keuangan\InputMemorialController;
use App\Http\Controllers\keuangan\HarianLepasController;
use App\Http\Controllers\keuangan\FotoBonController;
use App\Http\Controllers\keuangan\LaporanBankUrutVoucherController;
use App\Http\Controllers\keuangan\LaporanChBgBelumKliringController;
use App\Http\Controllers\keuangan\LaporanKwitansiLunasController;
use App\Http\Controllers\keuangan\LaporanInputKasController;
use App\Http\Controllers\administrasi\LaporanInvoiceTerbitController;
use App\Http\Controllers\ComingSoonController;
// SURAT RAWAT JALAN
use App\Http\Controllers\administrasi\SuratRawatJalanController;
use App\Http\Controllers\administrasi\LaporanUnitRawatJalanController;
// NOTIFIKASI
use App\Http\Controllers\NotifikasiController;
// MANUAL BOOK
use App\Http\Controllers\ManualBookController;

Route::get('/', function () {
  // return view('content.authentications.auth-login-basic');
  return redirect()->route('login');
});

// Show login form (guest only)
Route::middleware('guest')->group(function () {
  Route::get('/login', [Login::class, 'index'])->name('login');
  Route::post('/login', [Login::class, 'postlogin'])->name('postlogin');
  Route::get('/forgot-password', [ForgotPassword::class, 'index'])->name('forgot-password');
});

Route::middleware(['auth'])->group(function () {
    Route::get('/akun/ubah-sandi', [UbahSandiController::class, 'UbahSandi'])->name('akun-ubah-sandi');
    Route::resource('/ubah-sandi', UbahSandiController::class);
    Route::get('/logout2', [Logout::class, 'index'])->name('logout2');
});

Route::group(
  ['middleware' => ['auth', 'check.password']],
  function () {
    Route::group(['middleware' => ['verified']], function () {

      Route::get('/coming-soon', [ComingSoonController::class, 'ComingSoon'])->name('coming-soon');
      Route::get('/api/cabangs', CabangController::class);

      Route::get('/home', [DashboardController::class, 'Dashboard'])->name('home');
      Route::get('/change-cabang/{id}', [ChangeCabangController::class, 'index'])->name('change-cabang');
      Route::get('/akun/profil', [ProfilController::class, 'Profil'])->name('akun-profil');
      
      Route::resource('/home-list', DashboardController::class);

      ## Modul Pengaturan / Setting
      Route::get('/setting/profile-perusahaan', [ProfilePerusahaanController::class, 'ProfilePerusahaan'])->name('setting-profile-perusahaan');
      Route::get('/setting/karyawan', [KaryawanController::class, 'Karyawan'])->name('setting-karyawan');
      Route::get('/setting/karyawan-lihat-foto', [KaryawanController::class, 'getFotoKaryawan']);
      Route::get('/setting/karyawan-hapus-foto', [KaryawanController::class, 'hapusFotoKaryawan']);
      Route::get('/setting/download-file-karyawan', [KaryawanController::class, 'downloadFile'])->name('setting-download-file-karyawan');
      Route::get('/setting/akses-registrasi-user', [RegistrasiUser::class, 'RegistrasiUser'])->name('setting-akses-registrasi-user');
      Route::get('/setting/download-file-user', [RegistrasiUser::class, 'downloadFile'])->name('setting-download-file-user');
      Route::get('/setting/akses-menu', [MenuController::class, 'Menu'])->name('setting-akses-menu');
      Route::get('/setting/akses-group', [GroupController::class, 'Group'])->name('setting-akses-group');
      Route::get('/setting/akses-user-privilege', [UserPrivilegeController::class, 'UserPrivilege'])->name('setting-akses-user-privilege');
      Route::get('/setting/akses-group-privilege', [GroupPrivilegeController::class, 'GroupPrivilege'])->name('setting-akses-group-privilege');
      Route::get('/setting/akses-cabang-privilege', [CabangPrivilegeController::class, 'CabangPrivilege'])->name('setting-akses-cabang-privilege');
      Route::get('/setting/periode-pembukuan', [PeriodePembukuanController::class, 'PeriodePembukuan'])->name('setting-periode-pembukuan');
      Route::get('/setting/penomoran-transaksi', [PenomoranTransaksiController::class, 'PenomoranTransaksi'])->name('setting-penomoran-transaksi');
      Route::get('/setting/printer', [PrinterController::class, 'Printer'])->name('setting-printer');
      Route::get('/setting/pengumuman', [PengumumanController::class, 'Pengumuman'])->name('setting-pengumuman');
      Route::get('/setting/jenis-pekerjaan', [JenisPekerjaanController::class, 'JenisPekerjaan'])->name('setting-jenis-pekerjaan');
      Route::get('/setting/panel-pekerjaan', [PanelPekerjaanController::class, 'PanelPekerjaan'])->name('setting-panel-pekerjaan');
      Route::get('/setting/posisi-pekerjaan', [PosisiPekerjaanController::class, 'PosisiPekerjaan'])->name('setting-posisi-pekerjaan');
      Route::get('/setting/tarif-ppn', [TarifPpnController::class, 'TarifPPN'])->name('setting-tarif-ppn');
      Route::get('/setting/coa', [CoaController::class, 'Coa'])->name('setting-coa');
      Route::get('/setting/backup-database', [BackupDBController::class, 'BackupDB'])->name('setting-backup-database');
      Route::get('/setting/jenis-kendaraan', [JenisKendaraanController::class, 'JenisKendaraan'])->name('setting-jenis-kendaraan');
      Route::get('/setting/merek-kendaraan', [MerekKendaraanController::class, 'MerekKendaraan'])->name('setting-merek-kendaraan');
      Route::get('/setting/tipe-kendaraan', [TipeKendaraanController::class, 'TipeKendaraan'])->name('setting-tipe-kendaraan');
      Route::get('/setting/log-activity', [LogActivityController::class, 'LogActivity'])->name('setting-log-activity');
      Route::get('/setting/login-activity', [LoginActivityController::class, 'LoginActivity'])->name('setting-login-activity');
      Route::get('/setting/parameter', [ParameterController::class, 'Parameter'])->name('setting-parameter');
      
      Route::resource('/profile-list', ProfilePerusahaanController::class);
      Route::resource('/karyawan-list', KaryawanController::class);
      Route::resource('/registrasi-user-list', RegistrasiUser::class);
      Route::resource('/menu-list', MenuController::class);
      Route::resource('/group-list', GroupController::class);
      Route::resource('/user-privilege-list', UserPrivilegeController::class);
      Route::resource('/group-privilege-list', GroupPrivilegeController::class);
      Route::resource('/cabang-privilege-list', CabangPrivilegeController::class);
      Route::resource('/periode-pembukuan-list', PeriodePembukuanController::class);
      Route::resource('/penomoran-transaksi-list', PenomoranTransaksiController::class);
      Route::resource('/printer-list', PrinterController::class);
      Route::resource('/pengumuman-list', PengumumanController::class);
      Route::resource('/jenis-pekerjaan-list', JenisPekerjaanController::class);
      Route::resource('/panel-pekerjaan-list', PanelPekerjaanController::class);
      Route::resource('/posisi-pekerjaan-list', PosisiPekerjaanController::class);
      Route::resource('/tarif-ppn-list', TarifPpnController::class);
      Route::resource('/coa-list', CoaController::class);
      Route::resource('/backup-db-list', BackupDBController::class);
      Route::resource('/jenis-kendaraan-list', JenisKendaraanController::class);
      Route::resource('/merek-kendaraan-list', MerekKendaraanController::class);
      Route::resource('/tipe-kendaraan-list', TipeKendaraanController::class);
      Route::resource('/log-activity-list', LogActivityController::class);
      Route::resource('/login-activity-list', LoginActivityController::class);
      Route::resource('/parameter-list', ParameterController::class);

      ## Modul Customer Service
      Route::get('/customer-service/input-data-pemilik', [PemilikController::class, 'Pemilik'])->name('customer-service-input-data-pemilik');
      Route::get('/customer-service/download-file-pemilik', [PemilikController::class, 'downloadFile'])->name('customer-service-download-file-pemilik');
      Route::get('/customer-service/input-data-kendaraan', [KendaraanController::class, 'Kendaraan'])->name('customer-service-input-data-kendaraan');
      Route::get('/customer-service/get-tipe-kendaraan', [KendaraanController::class, 'getTipeKendaraan']);
      Route::get('/customer-service/get-kendaraan/{id}', [KendaraanController::class, 'getKendaraan']);
      Route::get('/customer-service/get-pemilik/{id}', [KendaraanController::class, 'getPemilik']);
      Route::get('/customer-service/get-foto-stnk', [KendaraanController::class, 'getFotoSTNK']);
      Route::delete('/customer-service/hapus-foto-stnk/{id}', [KendaraanController::class, 'hapusFotoSTNK']);
      Route::get('/customer-service/input-data-asuransi', [AsuransiController::class, 'Asuransi'])->name('customer-service-input-data-asuransi');
      Route::get('/customer-service/get-nama-asuransi', [AsuransiController::class, 'getNamaAsuransi']);
      Route::get('/customer-service/input-data-pelanggan', [PelangganController::class, 'Pelanggan'])->name('customer-service-input-data-pelanggan');
      Route::get('/customer-service/download-file-pelanggan', [PelangganController::class, 'downloadFile'])->name('customer-service-download-file-pelanggan');
      Route::get('/customer-service/get-nama-pelanggan', [PelangganController::class, 'getNamaPelanggan']);
      Route::get('/customer-service/input-data-marketing', [MarketingController::class, 'Marketing'])->name('customer-service-input-data-marketing');
      Route::get('/customer-service/input-data-perantara', [PerantaraController::class, 'Perantara'])->name('customer-service-input-data-perantara');
      Route::get('/customer-service/spk', [SpkController::class, 'SPK'])->name('customer-service-spk');
      Route::get('/customer-service/spk-batal', [SpkBatalController::class, 'SPK'])->name('customer-service-spk-batal');
      Route::get('/customer-service/spk-tutup', [SpkTutupController::class, 'SPK'])->name('customer-service-spk-tutup');
      Route::get('/customer-service/spk-keluar', [SpkKeluarController::class, 'SPK'])->name('customer-service-spk-keluar');
      Route::get('/customer-service/cetak-spk-keluar', [SpkKeluarController::class, 'cetakKendaraanKeluar'])->name('customer-service-cetak-spk-keluar');
      Route::get('/customer-service/invoice-or', [InvoiceOrController::class, 'InvoiceOr'])->name('customer-service-invoice-or');
      Route::get('/customer-service/cetak-invoice-or', [InvoiceOrController::class, 'cetakInvoice'])->name('customer-service-cetak-invoice-or');
      Route::get('/customer-service/tanda-terima-invoice-or', [TandaTerimaInvoiceOrController::class, 'TandaTerimaInvoiceOr'])->name('customer-service-tanda-terima-invoice-or');
      Route::get('/customer-service/cetak-tanda-terima-invoice-or', [TandaTerimaInvoiceOrController::class, 'cetakInvoice'])->name('customer-service-cetak-tanda-terima-invoice-or');
      Route::get('/customer-service/laporan-spk', [LaporanSpkController::class, 'LaporanSPK'])->name('customer-service-laporan-spk');
      Route::get('/customer-service/laporan-kendaraan', [LaporanKendaraanController::class, 'LaporanKendaraan'])->name('customer-service-laporan-kendaraan');
      Route::get('/customer-service/laporan-posisi-perbaikan', [LaporanPosisiPerbaikanController::class, 'LaporanPosisiPerbaikan'])->name('customer-service-laporan-posisi-perbaikan');
      Route::get('/customer-service/laporan-invoice', [LaporanInvoiceController::class, 'LaporanInvoice'])->name('customer-service-laporan-invoice');
      Route::get('/customer-service/laporan-outstanding', [LaporanOutstandingController::class, 'LaporanOutstanding'])->name('customer-service-laporan-outstanding');
      Route::get('/customer-service/laporan-kwitansi', [LaporanKwitansiController::class, 'LaporanKwitansi'])->name('customer-service-laporan-kwitansi');
      Route::get('/customer-service/cetak-invoice-or-filter', [InvoiceOrController::class, 'cetakInvoiceFilter'])->name('customer-service-cetak-invoice-or-filter');
      Route::get('laporan-spk/customer-list', [LaporanSpkController::class, 'customerList']);

      Route::resource('/pemilik-list', PemilikController::class);
      Route::resource('/kendaraan-list', KendaraanController::class);
      Route::resource('/asuransi-list', AsuransiController::class);
      Route::resource('/pelanggan-list', PelangganController::class);
      Route::resource('/marketing-list', MarketingController::class);
      Route::resource('/perantara-list', PerantaraController::class);
      Route::resource('/spk-list', SpkController::class);
      Route::resource('/spk-batal-list', SpkBatalController::class);
      Route::resource('/spk-tutup-list', SpkTutupController::class);
      Route::resource('/spk-keluar-list', SpkKeluarController::class);
      Route::resource('/invoice-or-list', InvoiceOrController::class);
      Route::resource('/tanda-terima-invoice-or-list', TandaTerimaInvoiceOrController::class);
      Route::resource('/laporan-spk-list', LaporanSpkController::class);
      Route::resource('/laporan-kendaraan-list', LaporanKendaraanController::class);
      Route::resource('/laporan-posisi-perbaikan-list', LaporanPosisiPerbaikanController::class);
      Route::resource('/laporan-invoice-list', LaporanInvoiceController::class);
      Route::resource('/laporan-outstanding-list', LaporanOutstandingController::class);
      Route::resource('/laporan-kwitansi-list', LaporanKwitansiController::class);

      Route::get('laporan-spk/export', [LaporanSpkController::class, 'exportExcel'])->name('laporan-spk.export');
      Route::get('laporan-kendaraan/export', [LaporanKendaraanController::class, 'exportExcel'])->name('laporan-kendaraan.export');
      Route::get('laporan-posisi-perbaikan/export', [LaporanPosisiPerbaikanController::class, 'exportExcel'])->name('laporan-posisi-perbaikan.export');
      Route::get('laporan-invoice/export', [LaporanInvoiceController::class, 'exportExcel'])->name('laporan-invoice.export');
      Route::get('laporan-outstanding/export', [LaporanOutstandingController::class, 'exportExcel'])->name('laporan-outstanding.export');
      Route::get('laporan-kwitansi/export', [LaporanKwitansiController::class, 'exportExcel'])->name('laporan-kwitansi.export');
      
      Route::get('laporan-spk/print', [LaporanSpkController::class, 'printData'])->name('laporan-spk.print');
      Route::get('laporan-kendaraan/print', [LaporanKendaraanController::class, 'printData'])->name('laporan-kendaraan.print');
      Route::get('laporan-posisi-perbaikan/print', [LaporanPosisiPerbaikanController::class, 'printData'])->name('laporan-posisi-perbaikan.print');
      Route::get('laporan-invoice/print', [LaporanInvoiceController::class, 'printData'])->name('laporan-invoice.print');
      Route::get('laporan-outstanding/print', [LaporanOutstandingController::class, 'printData'])->name('laporan-outstanding.print');
      Route::get('laporan-kwitansi/print', [LaporanKwitansiController::class, 'printData'])->name('laporan-kwitansi.print');

      ## Modul Administrasi
      Route::get('/administrasi/upload-foto-pekerjaan', [FotoPekerjaanController::class, 'FotoPekerjaan'])->name('administrasi-upload-foto-pekerjaan');
      // Route::get('/administrasi/spk-photos/image/{id}', [FotoPekerjaanController::class, 'renderImage'])->name('photo.render');
      Route::get('/administrasi/get-foto-pekerjaan', [FotoPekerjaanController::class, 'getFotoPekerjaan']);
      Route::get('/administrasi/konsep-estimasi', [KonsepEstimasiController::class, 'KonsepEstimasi'])->name('administrasi-konsep-estimasi');
      Route::get('/administrasi/cetak-konsep-estimasi', [KonsepEstimasiController::class, 'cetakKonsepEstimasi'])->name('administrasi-cetak-konsep-estimasi');
      Route::get('/administrasi/estimasi', [EstimasiController::class, 'Estimasi'])->name('administrasi-estimasi');
      Route::get('/administrasi/cetak-estimasi', [EstimasiController::class, 'cetakEstimasi'])->name('administrasi-cetak-estimasi');
      Route::get('/administrasi/export-estimasi', [EstimasiController::class, 'exportExcel'])->name('administrasi-export-estimasi');
      Route::get('/administrasi/kirim-estimasi', [KirimEstimasiController::class, 'KirimEstimasi'])->name('administrasi-kirim-estimasi');
      Route::get('/administrasi/kewajiban-tertanggung', [KewajibanController::class, 'Kewajiban'])->name('administrasi-kewajiban-tertanggung');
      Route::get('/administrasi/jadwal-turun-lapangan', [JadwalTurunLapController::class, 'JadwalTurunLap'])->name('administrasi-jadwal-turun-lapangan');
      Route::get('/administrasi/progress-kerja', [ProgressKerjaController::class, 'ProgressKerja'])->name('administrasi-progress-kerja');
      Route::get('/administrasi/posisi-perbaikan', [PosisiPerbaikanController::class, 'PosisiPerbaikan'])->name('administrasi-posisi-perbaikan');
      Route::get('/administrasi/posisi-perbaikan-export', [PosisiPerbaikanController::class, 'exportExcel'])->name('administrasi-posisi-perbaikan.export');
      Route::get('/administrasi/estimasi-disetujui', [EstimasiDisetujuiController::class, 'EstimasiDisetujui'])->name('administrasi-estimasi-disetujui');
      Route::get('/administrasi/salvage', [SalvageController::class, 'Salvage'])->name('administrasi-salvage');
      Route::get('/administrasi/cetak-salvage', [SalvageController::class, 'cetakSalvage'])->name('administrasi-cetak-salvage');
      Route::get('/administrasi/kirim-salvage', [KirimSalvageController::class, 'KirimSalvage'])->name('administrasi-kirim-salvage');
      Route::get('/administrasi/invoice-asuransi-pribadi', [InvoiceController::class, 'Invoice'])->name('administrasi-invoice-asuransi-pribadi');
      Route::get('/administrasi/terima-dokumen', [TerimaDokumenKlaimController::class, 'TerimaDokumenKlaim'])->name('administrasi-terima-dokumen');
      Route::get('/administrasi/tanda-terima-invoice', [TandaTerimaInvoiceController::class, 'TandaTerimaInvoice'])->name('administrasi-tanda-terima-invoice');
      Route::get('/administrasi/cetak-tanda-terima-invoice', [TandaTerimaInvoiceController::class, 'cetakInvoice'])->name('administrasi-cetak-tanda-terima-invoice');
      Route::get('/administrasi/cetak-invoice', [InvoiceController::class, 'printInvoice'])->name('administrasi-cetak-invoice');
      Route::get('/administrasi/laporan-estimasi-belum-dibuat', [LaporanEstimasiBelumDibuatController::class, 'LaporanEstimasiBelumDibuat'])->name('administrasi-laporan-estimasi-belum-dibuat');
      Route::get('/administrasi/laporan-estimasi-belum-dikirim', [LaporanEstimasiBelumDikirimController::class, 'LaporanEstimasiBelumDikirim'])->name('administrasi-laporan-estimasi-belum-dikirim');
      Route::get('/administrasi/laporan-rekap-estimasi', [LaporanRekapEstimasiController::class, 'LaporanRekapEstimasi'])->name('administrasi-laporan-rekap-estimasi');
      Route::get('/administrasi/laporan-rincian-estimasi', [LaporanRincianEstimasiController::class, 'LaporanRincianEstimasi'])->name('administrasi-laporan-rincian-estimasi');
      Route::get('/administrasi/laporan-estimasi-per-tahun', [LaporanEstimasiPerTahunController::class, 'LaporanEstimasiPerTahun'])->name('administrasi-laporan-estimasi-per-tahun');
      Route::get('/administrasi/laporan-estimasi-disetujui', [LaporanEstimasiDisetujuiController::class, 'LaporanEstimasiDisetujui'])->name('administrasi-laporan-estimasi-disetujui');
      Route::get('/administrasi/laporan-insentif-kwitansi', [LaporanInsentifKwitansiController::class, 'LaporanInsentifKwitansi'])->name('administrasi-laporan-insentif-kwitansi');
      Route::get('/administrasi/laporan-insentif-pembayaran', [LaporanInsentifPembayaranController::class, 'LaporanInsentifPembayaran'])->name('administrasi-laporan-insentif-pembayaran');
      Route::get('/administrasi/laporan-insentif-marketing', [LaporanInsentifMarketingController::class, 'LaporanInsentifMarketing'])->name('administrasi-laporan-insentif-marketing');
      Route::get('/administrasi/laporan-insentif-st', [LaporanInsentifSTController::class, 'LaporanInsentifST'])->name('administrasi-laporan-insentif-st');
      Route::get('/administrasi/laporan-aging-penawaran', [LaporanAgingPenawaranController::class, 'LaporanAgingPenawaran'])->name('administrasi-laporan-aging-penawaran');
      Route::get('/administrasi/laporan-aging-penagihan', [LaporanAgingPenagihanController::class, 'LaporanAgingPenagihan'])->name('administrasi-laporan-aging-penagihan');
      Route::get('/administrasi/laporan-komisi-surveyor', [LaporanKomisiSurveyorController::class, 'LaporanKomisiSurveyor'])->name('administrasi-laporan-komisi-surveyor');
      Route::get('/administrasi/laporan-rekap-point-panel', [LaporanRekapPointPanelController::class, 'LaporanRekapPointPanel'])->name('administrasi-laporan-rekap-point-panel');
      
      Route::resource('/foto-pekerjaan-list', FotoPekerjaanController::class);
      Route::resource('/konsep-estimasi-list', KonsepEstimasiController::class);
      Route::resource('/estimasi-list', EstimasiController::class);
      Route::resource('/kirim-estimasi-list', KirimEstimasiController::class);
      Route::resource('/kewajiban-list', KewajibanController::class);
      Route::resource('/jadwal-turun-lapangan-list', JadwalTurunLapController::class);
      Route::resource('/progress-kerja-list', ProgressKerjaController::class);
      Route::resource('/posisi-perbaikan-list', PosisiPerbaikanController::class);
      Route::resource('/estimasi-disetujui-list', EstimasiDisetujuiController::class);
      Route::resource('/salvage-list', SalvageController::class);
      Route::resource('/kirim-salvage-list', KirimSalvageController::class);
      Route::resource('/invoice-list', InvoiceController::class);
      Route::resource('/tanda-terima-invoice-list', TandaTerimaInvoiceController::class);
      Route::resource('/terima-dokumen-klaim-list', TerimaDokumenKlaimController::class);
      Route::resource('/laporan-estimasi-dibuat-list', LaporanEstimasiBelumDibuatController::class);
      Route::resource('/laporan-estimasi-dikirim-list', LaporanEstimasiBelumDikirimController::class);
      Route::resource('/laporan-rekap-estimasi-list', LaporanRekapEstimasiController::class);
      Route::resource('/laporan-rincian-estimasi-list', LaporanRincianEstimasiController::class);
      Route::resource('/laporan-estimasi-tahun-list', LaporanEstimasiPerTahunController::class);
      Route::resource('/laporan-estimasi-disetujui-list', LaporanEstimasiDisetujuiController::class);
      Route::resource('/laporan-insentif-kwitansi-list', LaporanInsentifKwitansiController::class);
      Route::resource('/laporan-insentif-pembayaran-list',LaporanInsentifPembayaranController::class);
      Route::resource('/laporan-insentif-marketing-list', LaporanInsentifMarketingController::class);
      Route::resource('/laporan-insentif-st-list', LaporanInsentifSTController::class);
      Route::resource('/laporan-aging-penawaran-list', LaporanAgingPenawaranController::class);
      Route::resource('/laporan-aging-penagihan-list', LaporanAgingPenagihanController::class);
      Route::resource('/laporan-komisi-surveyor-list', LaporanKomisiSurveyorController::class);
      Route::resource('/laporan-rekap-point-panel-list', LaporanRekapPointPanelController::class);
      
      Route::get('laporan-estimasi-belum-dibuat/export', [LaporanEstimasiBelumDibuatController::class, 'exportExcel'])->name('laporan-estimasi-belum-dibuat.export');
      Route::get('laporan-estimasi-dikirim/export', [LaporanEstimasiBelumDikirimController::class, 'exportExcel'])->name('laporan-estimasi.export');
      Route::get('laporan-rekap-estimasi/export', [LaporanRekapEstimasiController::class, 'exportExcel'])->name('laporan-rekap-estimasi.export');
      Route::get('laporan-rincian-estimasi/export', [LaporanRincianEstimasiController::class, 'exportExcel'])->name('laporan-rincian-estimasi.export');
      Route::get('laporan-estimasi-tahun/export', [LaporanEstimasiPerTahunController::class, 'exportExcel'])->name('laporan-estimasi-tahun.export');
      Route::get('laporan-estimasi-disetujui/export', [LaporanEstimasiDisetujuiController::class, 'exportExcel'])->name('laporan-estimasi-disetujui.export');
      Route::get('laporan-insentif-kwitansi/export', [LaporanInsentifKwitansiController::class, 'exportExcel'])->name('laporan-insentif-kwitansi.export');
      Route::get('laporan-insentif-pembayaran/export', [LaporanInsentifPembayaranController::class, 'exportExcel'])->name('laporan-insentif-pembayaran.export');
      Route::get('laporan-insentif-marketing/export', [LaporanInsentifMarketingController::class, 'exportExcel'])->name('laporan-insentif-marketing.export');
      Route::get('laporan-insentif-st/export', [LaporanInsentifSTController::class, 'exportExcel'])->name('laporan-insentif-st.export');
      Route::get('laporan-aging-penawaran/export', [LaporanAgingPenawaranController::class, 'exportExcel'])->name('laporan-aging-penawaran.export');
      Route::get('laporan-aging-penagihan/export', [LaporanAgingPenagihanController::class, 'exportExcel'])->name('laporan-aging-penagihan.export');
      Route::get('laporan-komisi-surveyor/export', [LaporanKomisiSurveyorController::class, 'exportExcel'])->name('laporan-komisi-surveyor.export');
      Route::get('laporan-rekap-point-panel/export', [LaporanRekapPointPanelController::class, 'exportExcel'])->name('laporan-rekap-point-panel.export');
      
      Route::get('laporan-estimasi-belum-dibuat/print', [LaporanEstimasiBelumDibuatController::class, 'printData'])->name('laporan-estimasi-belum-dibuat.print');
      Route::get('laporan-estimasi-dikirim/print', [LaporanEstimasiBelumDikirimController::class, 'printData'])->name('laporan-estimasi.print');
      Route::get('laporan-rekap-estimasi/print', [LaporanRekapEstimasiController::class, 'printData'])->name('laporan-rekap-estimasi.print');
      Route::get('laporan-rincian-estimasi/print', [LaporanRincianEstimasiController::class, 'printData'])->name('laporan-rincian-estimasi.print');
      Route::get('laporan-estimasi-tahun/print', [LaporanEstimasiPerTahunController::class, 'printData'])->name('laporan-estimasi-tahun.print');
      Route::get('laporan-estimasi-disetujui/print', [LaporanEstimasiDisetujuiController::class, 'printData'])->name('laporan-estimasi-disetujui.print');
      Route::get('laporan-insentif-kwitansi/print', [LaporanInsentifKwitansiController::class, 'printData'])->name('laporan-insentif-kwitansi.print');
      Route::get('laporan-insentif-pembayaran/print', [LaporanInsentifPembayaranController::class, 'printData'])->name('laporan-insentif-pembayaran.print');
      Route::get('laporan-insentif-marketing/print', [LaporanInsentifMarketingController::class, 'printData'])->name('laporan-insentif-marketing.print');
      Route::get('laporan-insentif-st/print', [LaporanInsentifSTController::class, 'printData'])->name('laporan-insentif-st.print');
      Route::get('laporan-aging-penawaran/print', [LaporanAgingPenawaranController::class, 'printData'])->name('laporan-aging-penawaran.print');
      Route::get('laporan-aging-penagihan/print', [LaporanAgingPenagihanController::class, 'printData'])->name('laporan-aging-penagihan.print');
      Route::get('laporan-komisi-surveyor/print', [LaporanKomisiSurveyorController::class, 'printData'])->name('laporan-komisi-surveyor.print');
      Route::get('laporan-rekap-point-panel/print', [LaporanRekapPointPanelController::class, 'printData'])->name('laporan-rekap-point-panel.print');
      // SURAT RAWAT JALAN
      Route::get('/administrasi/surat-rawat-jalan', [SuratRawatJalanController::class, 'SuratRawatJalan'])->name('administrasi-surat-rawat-jalan');
      Route::get('/administrasi/cetak-surat-rawat-jalan', [SuratRawatJalanController::class, 'cetakSurat'])->name('administrasi-cetak-surat-rawat-jalan');
      Route::resource('/surat-rawat-jalan-list', SuratRawatJalanController::class);
      // LAPORAN SURAT RAWAT JALAN
      Route::get('/administrasi/laporan-unit-rawat-jalan', [LaporanUnitRawatJalanController::class, 'LaporanUnitRawatJalan'])->name('administrasi-laporan-unit-rawat-jalan');
      Route::get('/laporan-unit-rawat-jalan/export', [LaporanUnitRawatJalanController::class, 'exportExcel'])->name('laporan-unit-rawat-jalan.export');
      Route::get('/laporan-unit-rawat-jalan/print', [LaporanUnitRawatJalanController::class, 'printData'])->name('laporan-unit-rawat-jalan.print');
      Route::resource('/laporan-unit-rawat-jalan-list', LaporanUnitRawatJalanController::class);

      ## Modul Gudang
      Route::get('/gudang-input/bahan', [BahanController::class, 'Bahan'])->name('gudang-input-bahan');
      Route::get('/gudang-input/sparepart', [SparepartController::class, 'Sparepart'])->name('gudang-input-sparepart');
      Route::get('/gudang-input/cat', [CatController::class, 'Cat'])->name('gudang-input-cat');
      Route::get('/gudang-input/pemasok', [PemasokController::class, 'Pemasok'])->name('gudang-input-pemasok');
      Route::get('/gudang-input/download-file-pemasok', [PemasokController::class, 'downloadFile'])->name('gudang-input-download-file-pemasok');
      Route::get('/gudang-input/umum', [UmumController::class, 'Umum'])->name('gudang-input-umum');
      Route::get('/gudang/pemakaian-bahan', [PemakaianBahanController::class, 'PemakaianBahan'])->name('gudang-pemakaian-bahan');
      Route::get('/gudang/permintaan-barang', [PermintaanBarangController::class, 'PermintaanBarang'])->name('gudang-permintaan-barang');
      Route::get('/gudang/permintaan-barang-cek-spk', [PermintaanBarangController::class, 'getDataSPK'])->name('gudang-permintaan-barang-cek-spk');
      Route::get('/gudang/cetak-permintaan-barang', [PermintaanBarangController::class, 'cetakPermintaanBarang'])->name('gudang-cetak-permintaan-barang');
      Route::get('/gudang/order-pembelian', [OrderPembelianController::class, 'OrderPembelian'])->name('gudang-order-pembelian');
      Route::get('/gudang/order-pembelian-cek-spk', [OrderPembelianController::class, 'getDataSPK'])->name('gudang-order-pembelian-cek-spk');
      Route::get('/gudang/order-pembelian-cari-bahan', [OrderPembelianController::class, 'cariBahan'])->name('gudang-order-pembelian-cari-bahan');
      Route::get('/gudang/entry-pembelian', [InputPembelianController::class, 'InputPembelian'])->name('gudang-entry-pembelian');
      Route::get('/gudang/entry-pembelian-cek-spk', [InputPembelianController::class, 'getDataOrder'])->name('gudang-entry-pembelian-cek-spk');
      Route::get('/gudang/retur-pembelian', [ReturPembelianController::class, 'ReturPembelian'])->name('gudang-retur-pembelian');
      Route::get('/gudang/retur-pembelian-cek-spk', [ReturPembelianController::class, 'getDataInputGudang'])->name('gudang-retur-pembelian-cek-spk');
      Route::get('/gudang/pengeluaran-barang', [PengeluaranBarangController::class, 'PengeluaranBarang'])->name('gudang-pengeluaran-barang');
      Route::get('/gudang/pengeluaran-barang-cek-spk', [PengeluaranBarangController::class, 'getDataSPK'])->name('gudang-pengeluaran-barang-cek-spk');
      Route::get('/gudang/stock-opname', [StockOpnameController::class, 'StockOpname'])->name('gudang-stock-opname');
      Route::get('/gudang/stock-opname-export', [StockOpnameController::class, 'exportExcel'])->name('gudang-stock-opname-export');
      Route::get('/gudang/stock-opname-cek-saldo', [StockOpnameController::class, 'getDataSaldo'])->name('gudang-stock-opname-cek-saldo');
      Route::post('/gudang/konsolidasi-saldo', [StockOpnameController::class, 'konsolidasiSaldo'])->name('gudang-konsolidasi-saldo');
      Route::get('/gudang/tutup-buku', [TutupBukuController::class, 'TutupBuku'])->name('gudang-tutup-buku');
      Route::get('/gudang/get-nama-bahan', [PemakaianBahanController::class, 'getNamaBahan']);
      // Route::get('/gudang/get-spk', [OrderPembelianController::class, 'getDataSPK']);
      // Route::get('/gudang/get-permintaan', [OrderPembelianController::class, 'getDataPermintaan']);
      Route::get('/gudang/get-bagian', [PermintaanBarangController::class, 'getDataBagian']);
      Route::get('/gudang/order-pembelian-cetak', [OrderPembelianController::class, 'cetakOrderPembelian']);
      Route::get('/gudang/entry-pembelian-cetak', [InputPembelianController::class, 'cetakInputPembelian']);
      Route::get('/gudang/retur-pembelian-cetak', [ReturPembelianController::class, 'cetakReturPembelian']);
      Route::get('/gudang/pengeluaran-barang-cetak', [PengeluaranBarangController::class, 'cetakPengeluaranBarang']);
      Route::get('/gudang/laporan-pembelian-bahan', [LaporanPembelianBahanController::class, 'LaporanPembelianBahan'])->name('gudang-laporan-pembelian-bahan');
      Route::get('/gudang/laporan-pembelian-cat', [LaporanPembelianCatController::class, 'LaporanPembelianCat'])->name('gudang-laporan-pembelian-cat');
      Route::get('/gudang/laporan-pembelian-sparepart', [LaporanPembelianSparepartController::class, 'LaporanPembelianSparepart'])->name('gudang-laporan-pembelian-sparepart');
      Route::get('/gudang/laporan-gudang-bahan', [LaporanGudangBahanController::class, 'LaporanGudangBahan'])->name('gudang-laporan-gudang-bahan');
      Route::get('/gudang/laporan-gudang-cat', [LaporanGudangCatController::class, 'LaporanGudangCat'])->name('gudang-laporan-gudang-cat');
      Route::get('/gudang/laporan-gudang-sparepart', [LaporanGudangSparepartController::class, 'LaporanGudangSparepart'])->name('gudang-laporan-gudang-sparepart');
      Route::get('/gudang/laporan-pengeluaran-bahan', [LaporanPengeluaranBahanController::class, 'LaporanPengeluaranBahan'])->name('gudang-laporan-pengeluaran-bahan');
      Route::get('/gudang/laporan-pengeluaran-cat', [LaporanPengeluaranCatController::class, 'LaporanPengeluaranCat'])->name('gudang-laporan-pengeluaran-cat');
      Route::get('/gudang/laporan-pengeluaran-sparepart', [LaporanPengeluaranSparepartController::class, 'LaporanPengeluaranSparepart'])->name('gudang-laporan-pengeluaran-sparepart');
      Route::get('/gudang/laporan-retur-sparepart', [LaporanReturSparepartController::class, 'LaporanReturSparepart'])->name('gudang-laporan-retur-sparepart');
      Route::get('/gudang/laporan-analisa-pemakaian-bahan', [LaporanAnalisaPemakaianBahanController::class, 'LaporanAnalisaPemakaianBahan'])->name('gudang-laporan-analisa-pemakaian-bahan');
      Route::get('/gudang/laporan-analisa-pemakaian-cat', [LaporanAnalisaPemakaianCatController::class, 'LaporanAnalisaPemakaianCat'])->name('gudang-laporan-analisa-pemakaian-cat');
      Route::get('/gudang/laporan-kontrol-pemakaian-bahan', [LaporanKontrolPemakaianBahanController::class, 'LaporanKontrolPemakaianBahan'])->name('gudang-laporan-kontrol-pemakaian-bahan');

      Route::resource('/bahan-list', BahanController::class);
      Route::resource('/sparepart-list', SparepartController::class);
      Route::resource('/cat-list', CatController::class);
      Route::resource('/pemasok-list', PemasokController::class);
      Route::resource('/umum-list', UmumController::class);
      Route::resource('/pemakaian-bahan-list', PemakaianBahanController::class);
      Route::resource('/permintaan-barang-list', PermintaanBarangController::class);
      Route::resource('/order-pembelian-list', OrderPembelianController::class);
      Route::resource('/input-pembelian-list', InputPembelianController::class);
      Route::resource('/retur-pembelian-list', ReturPembelianController::class);
      Route::resource('/pengeluaran-barang-list', PengeluaranBarangController::class);
      Route::resource('/stock-opname-list', StockOpnameController::class);
      Route::resource('/tutup-buku-list', TutupBukuController::class);
      Route::resource('/laporan-pembelian-bahan-list', LaporanPembelianBahanController::class);
      Route::resource('/laporan-pembelian-cat-list', LaporanPembelianCatController::class);
      Route::resource('/laporan-pembelian-sparepart-list', LaporanPembelianSparepartController::class);
      Route::resource('/laporan-gudang-bahan-list', LaporanGudangBahanController::class);
      Route::resource('/laporan-gudang-cat-list', LaporanGudangCatController::class);
      Route::resource('/laporan-gudang-sparepart-list', LaporanGudangSparepartController::class);
      Route::resource('/laporan-pengeluaran-bahan-list', LaporanPengeluaranBahanController::class);
      Route::resource('/laporan-pengeluaran-cat-list', LaporanPengeluaranCatController::class);
      Route::resource('/lap-pengeluaran-sparepart-list', LaporanPengeluaranSparepartController::class);
      Route::resource('/laporan-retur-sparepart-list', LaporanReturSparepartController::class);
      Route::resource('/laporan-analisa-bahan-list', LaporanAnalisaPemakaianBahanController::class);
      Route::resource('/laporan-analisa-cat-list', LaporanAnalisaPemakaianCatController::class);
      Route::resource('/lap-kontrol-pemakaian-bahan-list', LaporanKontrolPemakaianBahanController::class);
      
      Route::get('laporan-pembelian-bahan/export', [LaporanPembelianBahanController::class, 'exportExcel'])->name('laporan-pembelian-bahan.export');
      Route::get('laporan-pembelian-cat/export', [LaporanPembelianCatController::class, 'exportExcel'])->name('laporan-pembelian-cat.export');
      Route::get('laporan-pembelian-sparepart/export', [LaporanPembelianSparepartController::class, 'exportExcel'])->name('laporan-pembelian-sparepart.export');
      Route::get('laporan-gudang-bahan/export', [LaporanGudangBahanController::class, 'exportExcel'])->name('laporan-gudang-bahan.export');
      Route::get('laporan-gudang-cat/export', [LaporanGudangCatController::class, 'exportExcel'])->name('laporan-gudang-cat.export');
      Route::get('laporan-gudang-sparepart/export', [LaporanGudangSparepartController::class, 'exportExcel'])->name('laporan-gudang-sparepart.export');
      Route::get('laporan-pengeluaran-bahan/export', [LaporanPengeluaranBahanController::class, 'exportExcel'])->name('laporan-pengeluaran-bahan.export');
      Route::get('laporan-pengeluaran-cat/export', [LaporanPengeluaranCatController::class, 'exportExcel'])->name('laporan-pengeluaran-cat.export');
      Route::get('lap-pengeluaran-sparepart/export', [LaporanPengeluaranSparepartController::class, 'exportExcel'])->name('lap-pengeluaran-sparepart.export');
      Route::get('laporan-retur-sparepart/export', [LaporanReturSparepartController::class, 'exportExcel'])->name('laporan-retur-sparepart.export');
      Route::get('laporan-analisa-bahan/export', [LaporanAnalisaPemakaianBahanController::class, 'exportExcel'])->name('laporan-analisa-bahan.export');
      Route::get('laporan-analisa-cat/export', [LaporanAnalisaPemakaianCatController::class, 'exportExcel'])->name('laporan-analisa-cat.export');
      Route::get('lap-kontrol-pemakaian-bahan/export', [LaporanKontrolPemakaianBahanController::class, 'exportExcel'])->name('lap-kontrol-pemakaian-bahan.export');

      Route::get('laporan-pembelian-bahan/print', [LaporanPembelianBahanController::class, 'printData'])->name('laporan-pembelian-bahan.print');
      Route::get('laporan-pembelian-cat/print', [LaporanPembelianCatController::class, 'printData'])->name('laporan-pembelian-cat.print');
      Route::get('laporan-pembelian-sparepart/print', [LaporanPembelianSparepartController::class, 'printData'])->name('laporan-pembelian-sparepart.print');
      Route::get('laporan-gudang-bahan/print', [LaporanGudangBahanController::class, 'printData'])->name('laporan-gudang-bahan.print');
      Route::get('laporan-gudang-cat/print', [LaporanGudangCatController::class, 'printData'])->name('laporan-gudang-cat.print');
      Route::get('laporan-gudang-sparepart/print', [LaporanGudangSparepartController::class, 'printData'])->name('laporan-gudang-sparepart.print');
      Route::get('laporan-pengeluaran-bahan/print', [LaporanPengeluaranBahanController::class, 'printData'])->name('laporan-pengeluaran-bahan.print');
      Route::get('laporan-pengeluaran-cat/print', [LaporanPengeluaranCatController::class, 'printData'])->name('laporan-pengeluaran-cat.print');
      Route::get('lap-pengeluaran-sparepart/print', [LaporanPengeluaranSparepartController::class, 'printData'])->name('lap-pengeluaran-sparepart.print');
      Route::get('laporan-retur-sparepart/print', [LaporanReturSparepartController::class, 'printData'])->name('laporan-retur-sparepart.print');
      Route::get('laporan-analisa-bahan/print', [LaporanAnalisaPemakaianBahanController::class, 'printData'])->name('laporan-analisa-bahan.print');
      Route::get('laporan-analisa-cat/print', [LaporanAnalisaPemakaianCatController::class, 'printData'])->name('laporan-analisa-cat.print');
      Route::get('lap-kontrol-pemakaian-bahan/print', [LaporanKontrolPemakaianBahanController::class, 'printData'])->name('lap-kontrol-pemakaian-bahan.print');

      ## Modul Keuangan
      Route::get('/keuangan/data-bank', [BankController::class, 'BanK'])->name('keuangan-data-bank');
      Route::get('/keuangan/data-rekening', [RekeningController::class, 'Rekening'])->name('keuangan-data-rekening');
      Route::get('/keuangan/bukti-penerimaan', [BuktiPenerimaanController::class, 'BuktiPenerimaan'])->name('keuangan-bukti-penerimaan');
      Route::get('/keuangan/cetak-bukti-penerimaan', [BuktiPenerimaanController::class, 'cetakBuktiPenerimaan'])->name('keuangan-cetak-bukti-penerimaan');
      Route::get('/keuangan/input-kas', [InputKasController::class, 'InputKas'])->name('keuangan-input-kas');
      Route::get('/keuangan/cek-spk', [InputKasController::class, 'getDataSPK'])->name('keuangan-cek-spk');
      Route::get('/keuangan/input-bank', [InputBankController::class, 'InputBank'])->name('keuangan-input-bank');
      Route::get('/keuangan/cetak-input-bank', [InputBankController::class, 'cetakBuktiPengeluaran'])->name('keuangan-cetak-input-bank');
      Route::get('/keuangan/history-spk', [HistorySpkController::class, 'HistorySpk'])->name('keuangan-history-spk');
      Route::get('/keuangan/uang-muka-penjualan', [UangMukaPenjualanController::class, 'UangMukaPenjualan'])->name('keuangan-uang-muka-penjualan');
      Route::get('/keuangan/uang-muka-pembelian', [UangMukaPembelianController::class, 'UangMukaPembelian'])->name('keuangan-uang-muka-pembelian');
      Route::get('/keuangan/penerimaan-gabungan', [PenerimaanGabunganController::class, 'PenerimaanGabungan'])->name('keuangan-penerimaan-gabungan');
      Route::get('/keuangan/pembayaran-gabungan', [PembayaranGabunganController::class, 'PembayaranGabungan'])->name('keuangan-pembayaran-gabungan');
      Route::get('/keuangan/pembayaran-harian-lepas', [HarianLepasController::class, 'HarianLepas'])->name('keuangan-pembayaran-harian-lepas');
      Route::get('/keuangan/cetak-harian-lepas', [HarianLepasController::class, 'printHarianLepas'])->name('keuangan-cetak-harian-lepas');
      Route::get('/keuangan/input-memorial', [InputMemorialController::class, 'InputMemorial'])->name('keuangan-input-memorial');
      Route::get('/keuangan/upload-foto-bon', [FotoBonController::class, 'FotoBon'])->name('keuangan-upload-foto-bon');
      Route::get('/keuangan/get-foto-bon', [FotoBonController::class, 'getFotoBon']);
      Route::get('/keuangan/laporan-bank-urut-voucher', [LaporanBankUrutVoucherController::class, 'LaporanBankUrutVoucher'])->name('keuangan-laporan-bank-urut-voucher');
      Route::get('/keuangan/laporan-ch-bg-belum-kliring', [LaporanChBgBelumKliringController::class, 'LaporanChBgBelumKliring'])->name('keuangan-laporan-ch-bg-belum-kliring');
      Route::get('/keuangan/laporan-kwitansi-lunas', [LaporanKwitansiLunasController::class, 'LaporanKwitansiLunas'])->name('keuangan-laporan-kwitansi-lunas');
      Route::get('/keuangan/laporan-input-kas', [LaporanInputKasController::class, 'LaporanInputKas'])->name('keuangan-laporan-input-kas');
      Route::get('/administrasi/laporan-invoice-terbit', [LaporanInvoiceTerbitController::class, 'LaporanInvoiceTerbit'])->name('administrasi-laporan-invoice-terbit');

      Route::resource('/bank-list', BankController::class);
      Route::resource('/rekening-list', RekeningController::class);
      Route::resource('/bukti-penerimaan-list', BuktiPenerimaanController::class);
      Route::resource('/input-kas-list', InputKasController::class);
      Route::resource('/input-bank-list', InputBankController::class);
      Route::resource('/history-spk-list', HistorySpkController::class);
      Route::resource('/uang-muka-penjualan-list', UangMukaPenjualanController::class);
      Route::resource('/uang-muka-pembelian-list', UangMukaPembelianController::class);
      Route::resource('/penerimaan-gabungan-list', PenerimaanGabunganController::class);
      Route::resource('/pembayaran-gabungan-list', PembayaranGabunganController::class);
      Route::resource('/input-memorial-list', InputMemorialController::class);
      Route::resource('/harian-lepas-list', HarianLepasController::class);
      Route::resource('/foto-bon-list', FotoBonController::class);
      Route::resource('/laporan-bank-urut-voucher-list', LaporanBankUrutVoucherController::class);
      Route::resource('/laporan-ch-bg-belum-kliring-list', LaporanChBgBelumKliringController::class);
      Route::resource('/laporan-kwitansi-lunas-list', LaporanKwitansiLunasController::class);
      Route::resource('/laporan-input-kas-list', LaporanInputKasController::class);
      Route::resource('/laporan-invoice-terbit-list', LaporanInvoiceTerbitController::class);

      Route::get('laporan-bank-urut-voucher/export', [LaporanBankUrutVoucherController::class, 'exportExcel'])->name('laporan-bank-urut-voucher.export');
      Route::get('laporan-ch-bg-belum-kliring/export', [LaporanChBgBelumKliringController::class, 'exportExcel'])->name('laporan-ch-bg-belum-kliring.export');
      Route::get('laporan-kwitansi-lunas/export', [LaporanKwitansiLunasController::class, 'exportExcel'])->name('laporan-kwitansi-lunas.export');
      Route::get('laporan-input-kas/export', [LaporanInputKasController::class, 'exportExcel'])->name('laporan-input-kas.export');
      Route::get('laporan-invoice-terbit/export', [LaporanInvoiceTerbitController::class, 'exportExcel'])->name('laporan-invoice-terbit.export');

      Route::get('laporan-bank-urut-voucher/print', [LaporanBankUrutVoucherController::class, 'printData'])->name('laporan-bank-urut-voucher.print');
      Route::get('laporan-ch-bg-belum-kliring/print', [LaporanChBgBelumKliringController::class, 'printData'])->name('laporan-ch-bg-belum-kliring.print');
      Route::get('laporan-kwitansi-lunas/print', [LaporanKwitansiLunasController::class, 'printData'])->name('laporan-kwitansi-lunas.print');
      Route::get('laporan-input-kas/print', [LaporanInputKasController::class, 'printData'])->name('laporan-input-kas.print');
      Route::get('laporan-invoice-terbit/print', [LaporanInvoiceTerbitController::class, 'printData'])->name('laporan-invoice-terbit.print');

      // NOTIFIKASI
      Route::get('/notifikasi', [NotifikasiController::class, 'index'])->name('notifikasi.index');
      Route::get('/notifikasi/semua', [NotifikasiController::class, 'semua'])->name('notifikasi.semua');
      Route::post('/notifikasi/read-all', [NotifikasiController::class, 'markAllRead'])->name('notifikasi.readAll');
      Route::post('/notifikasi/{id}/read', [NotifikasiController::class, 'markRead'])->name('notifikasi.read');
      Route::get('/notifikasi/digest-harian', [NotifikasiController::class, 'kirimDigestHarian'])->name('notifikasi.digestHarian');

      // MANUAL BOOK
      Route::get('/manual-book/cek', [ManualBookController::class, 'cek'])->name('manual-book.cek');
      Route::post('/manual-book/store', [ManualBookController::class, 'store'])->name('manual-book.store');
      Route::delete('/manual-book/destroy', [ManualBookController::class, 'destroy'])->name('manual-book.destroy');
      Route::get('/manual-book/view', [ManualBookController::class, 'view'])->name('manual-book.view');
      Route::get('/manual-book/flipbook', [ManualBookController::class, 'flipbook'])->name('manual-book.flipbook');
      Route::get('manual-book/download', [ManualBookController::class, 'download'])->name('manual-book.download');
    });
  });
