<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Spk extends Model
{
  protected $table = 't_spk_master';

  public $timestamps = true;

  protected $fillable = [
    'kode_cabang',
    'kode_spk',
    'tgl_masuk',
    'kode_status_spk',
    'no_polisi',
    'kode_merek',
    'kode_tipe',
    'pemilik',
    'alamat',
    'telepon',
    'kode_jenis_pelanggan',
    'kode_pelanggan',
    'kode_jenis_polis',
    'no_polis',
    'tertanggung',
    'harga_polis',
    'kode_claim',
    'harga_pasar',
    'ada_or',
    'ada_prorata',
    'prorata',
    'kode_or',
    'tanggal_or',
    'memo_or',
    'jumlah_or',
    'nilai_or',
    'total_or',
    'kode_voucher',
    'kode_pembayaran',
    'tanggal_lunas_or',
    'kode_lunas_or',
    'free',
    'memo',
    'berlaku_awal_polis',
    'berlaku_akhir_polis',
    'kode_perantara',
    'kode_perantara_id',
    'kode_marketing',
    'jenis_perbaikan',
    'catatan_khusus',
    'batal_by',
    'tgl_batal',
    'memo_batal',
    'kode_faktur',
    'tgl_faktur',
    'kode_keluar',
    'tgl_keluar',
    'kode_turun_lapangan',
    'tgl_turun_lapangan',
    'tgl_rencana_selesai',
    'yang_menyerahkan',
    'yang_menerima',
    'tgl_terima',
    'keterangan',
    'tgl_bongkar1',
    'tgl_bongkar2',
    'tgl_las1',
    'tgl_las2',
    'tgl_dempul1',
    'tgl_dempul2',
    'tgl_mixing1',
    'tgl_mixing2',
    'tgl_cat1',
    'tgl_cat2',
    'tgl_poles1',
    'tgl_poles2',
    'tgl_finishing1',
    'tgl_finishing2',
    'tgl_tanda_terima',
    // RAWAT JALAN
    'ada_rawat_jalan',
    'tgl_rawat_jalan1',
    'tgl_rawat_jalan2',
    // END RAWAT JALAN
    // HARIAN LEPAS
    'pekerja_las',
    'upah_las',
    'pekerja_dempul',
    'upah_dempul',
    // END HARIAN LEPAS
    'nama_penerima',
    'nama_pengantar',
    'uang_muka',
    'kode_tutup',
    'tanggal_tutup',
    'jumlah_panel',
    'status_spk',
    'no_work_order',
    'tgl_work_order',
    'no_invoice',
    'tgl_invoice',
    'ket_posisi',
    'print_invoice',
    'post_terbit_invoice',
    'post_lunas_invoice',
    'created_by',
    'updated_by'
  ];
}
